### ISSUE TITLE
How to mix custom renderer and vue renderer ?

### ISSUE THREAD

**Issue by klevron** [troisjs/trois-renderer#5]
My main concern when I was trying to make a custom renderer was : How to mix custom renderer and vue renderer ?

e.g. is is possible to simply render html or other libraries components : 

```html
<template>
  <!-- troisjs stuff -->
  <p>TEST</p>
</template>
```

**Comment by SaFrMo** [comment]
@klevron Update to this issue - I've managed to get a trois-renderer app working alongside an HTML app using an iframe and by creating separate Vue apps on the same page (which seems like an intended feature for Vue 3 - the dev tools allow switching between mounted apps and config methods are per-app rather than global). I've documented [here](https://trois-renderer-wip-docs.netlify.app/renderer/installation.html#in-html-apps) and will be closing this issue till a better fix like mixing renderers becomes available. Thanks!
